# Generated by Django 5.1.7 on 2025-03-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_otp_secret_alter_customuser_face_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="face_image",
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
    ]
