# Generated by Django 5.1.7 on 2025-03-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
