# Generated by Django 5.1.7 on 2025-03-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_generated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
